spring.application.name=transaction-service

server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/trace_transactions
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# JWT
jwt.secret=${JWT_SECRET:trace_super_secret_key_minimum_32_characters_long}
jwt.expiration=86400000


springdoc.api-docs.path=/transaction-service/v3/api-docs
springdoc.swagger-ui.enabled=false

springdoc.swagger-ui.servers[0].url=http://localhost:8080
springdoc.swagger-ui.servers[0].description=API Gateway




