spring.application.name=user-service
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/trace_users
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# JWT
jwt.secret=${JWT_SECRET:trace_super_secret_key_minimum_32_characters_long}
jwt.expiration=86400000

# Tells Springdoc to prefix its api-docs path with the service name
springdoc.api-docs.path=/user-service/v3/api-docs
springdoc.swagger-ui.enabled=false

springdoc.swagger-ui.servers[0].url=http://localhost:8080
springdoc.swagger-ui.servers[0].description=API Gateway
